canvas=document.getElementById("canvas1");
canvas.width=1250;
canvas.height=500;
context=canvas.getContext('2d');
class player{
    constructor(game){
        this.game=game;
        this.height=190;
        this.luckypointmax=1;
        this.luckypoint=0;
        this.levelup=false;
        this.levelupmaxtime=10000;
        this.leveluptime=0;
        this.width=120;
        this.x=25;
        this.y=0.3*this.game.height;
        this.miny=60;//this tells what is the limit of palyer to go to up 
        this.frameX=0;
        this.frameY=0;
        this.framemax=37;
        this.speed=5;
        this.collision=0;
        this.life=5;
        this.image=document.getElementById("player");
        this.score=0;
        this.enemyEscape=0;
        this.enemyEscapeMaxLimit=5;
        this.numberOfParticles=50;
        this.initalParticles=0;
    }
    draw(context){
        if(this.game.debug===true)context.strokeRect(this.x,this.y,this.width,this.height);
        context.drawImage(this.image,this.frameX*this.width,this.frameY*this.height,this.width,this.height,
            this.x,this.y,this.width,this.height);
    }
    update(deltatime){
        this.playermove();
        this.playercollision();
        this.levelupcheck(deltatime);
        this.checkDestruction();
    }
    playermove(){
        if(this.game.keys===-1)
            if((this.y+this.height)<this.game.height)
                this.y+=this.speed;
        if(this.game.keys===1)
            if(this.y>this.miny)
                this.y-=this.speed; 
        if(this.frameX<this.framemax)
            this.frameX++;
        else
            this.frameX=0;
    }
    playercollision(){
        this.game.enemy.enemies.forEach(enem=>{
            if(this.game.enemy.checkCollision(this,enem)){
                this.game.enemy.destroy(enem);
                if(enem.type==="whale")this.collision+=2;
                else this.collision++;
            }
        })
    }
    levelupcheck(deltatime){
        this.frameY=(this.levelup===true)?1:0;
        if(this.levelup===true){
            this.leveluptime+=deltatime;
        }
        if(this.leveluptime>=this.levelupmaxtime){
            this.speed-=3;
            this.leveluptime=0;
            this.levelup=false;
        }
        if(this.luckypoint>=this.luckypointmax){
            this.speed+=3;;
            this.levelup=true;
            this.luckypoint=0;
        }
    }
    checkDestruction(){
        if(this.collision>=this.life||this.enemyEscape>=this.enemyEscapeMaxLimit){
            this.game.gameover=true;
            this.selfDestroy();
            this.game.enemy.selfDestroy();
            this.game.start=false;
        }

    }
    selfDestroy(){
        while(this.initalParticles<this.numberOfParticles){
            this.game.particles.push(new particle(this.game,this.x,this.y,this.width,this.height))
            this.initalParticles++;
        }
    }
    initilize(){
        this.x=25;
        this.y=100;
        this.frameX=0;
        this.score=0;
        this.enemyEscape=0;
        this.collision=0;
        this.destroy=false;
        this.initalParticles=0;
    }
}
